stages:
  - pull_prod
  - build_prod
  - clear_prod

pull_code_prod:
  stage: pull_prod
  tags:
    - crm
  only:
    - main
  script:
    - cd /home/web/serp-search-backend/prod
    - sudo -H -u web git pull

build_prod:
  stage: build_prod
  tags:
    - crm
  only:
    - main
  script:
    - cd /home/web/serp-search-backend/prod
    - /usr/bin/docker compose -p seo-analyzer-prod -f docker-compose.prod.yml up --build -d

clear_prod:
  stage: clear_prod
  tags:
    - crm
  only:
    - main
  script:
    - cd /home/web
    - docker image prune -af
    - docker builder prune -af
